CREATE TRIGGER `TR_GENERAR_FICHA` AFTER INSERT ON `mas`
 FOR EACH ROW BEGIN 

INSERT INTO `aldeaanimal`.`ficha` (`ID_MAS`, `ESTERILIZACION`, `FECHA_ESTERILIZACION`, `FECHA_INGRESO`, `OBS_ESTERILIZACION`) VALUES (new.ID_MAS, NULL, NULL, CURRENT_DATE(), NULL);

END