CREATE TRIGGER `TR_PROTEGE_TIPO_PRES_UPD` BEFORE UPDATE ON `tipo_pres`
 FOR EACH ROW BEGIN
DECLARE TIPO int;
DECLARE specialty CONDITION FOR SQLSTATE '45000';
SET TIPO= OLD.ID_TIPO_PRES;
IF(TIPO=2) THEN
	SIGNAL SQLSTATE '45000'
    	SET MESSAGE_TEXT = 'Esa fila no se puede modificar';
        END IF;
END